name: Format checker (black)

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: RojerGS/python-black-check@master
       with:
        line-length: '81'
        path: '.'
        include: 'apps'
        exclude: '(/*.html|/*.mo|/*.po|/*.png|/*.rst)' 
